apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: did-storage
spec:
  forProvider:
    policy: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Sid": "VisualEditor0",
                  "Effect": "Allow",
                  "Action": [
                      "s3:GetBucketLocation",
                      "s3:ListBucket"
                  ],
                  "Resource": "arn:aws:s3:::awesomeapp-did-update-server-backup"
              },
              {
                  "Sid": "VisualEditor1",
                  "Effect": "Allow",
                  "Action": [
                      "s3:PutObject",
                      "s3:DeleteObject",
                      "s3:GetObject"
                  ],
                  "Resource": [
                      "arn:aws:s3:::awesomeapp-did-update-server-backup/*",
                      "arn:aws:s3:::awesomeapp-did-update-server-backup"
                  ]
              }
          ]
      }